//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiskoPersist.Resources
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class ErrorStrings {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ErrorStrings() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiskoPersist.Resources.ErrorStrings", typeof(ErrorStrings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Cannot generate cache key due to mismatch in key pairs..
		/// </summary>
		internal static string errCacheKeypairMismatch {
			get {
				return ResourceManager.GetString("errCacheKeypairMismatch", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Connection string is not defined.
		/// </summary>
		internal static string errConnectionSettingsNotDefined {
			get {
				return ResourceManager.GetString("errConnectionSettingsNotDefined", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Do not use arrays in messages. Use List&lt;T&gt;!.
		/// </summary>
		internal static string errDoNotUseArrays {
			get {
				return ResourceManager.GetString("errDoNotUseArrays", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Cannot create persistence object. Unknown connection type..
		/// </summary>
		internal static string errInvalicConnectionType {
			get {
				return ResourceManager.GetString("errInvalicConnectionType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Connection with name {0} not found.
		/// </summary>
		internal static string errInvalidConnectionString {
			get {
				return ResourceManager.GetString("errInvalidConnectionString", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to IOController must be set.
		/// </summary>
		internal static string errIOControllerIsNull {
			get {
				return ResourceManager.GetString("errIOControllerIsNull", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Unable to process the change to table {0} because another request for the same table has been submitted. If you still wish to process your change, you must refresh and then reprocess..
		/// </summary>
		internal static string errLockKeyFailed {
			get {
				return ResourceManager.GetString("errLockKeyFailed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Object does not exist. Cannot delete..
		/// </summary>
		internal static string errObjectDoesNotExist {
			get {
				return ResourceManager.GetString("errObjectDoesNotExist", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Cannot execute query. Sql is not set..
		/// </summary>
		internal static string errSqlNotSet {
			get {
				return ResourceManager.GetString("errSqlNotSet", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Table update failed.
		/// </summary>
		internal static string errTableUpdateFailed {
			get {
				return ResourceManager.GetString("errTableUpdateFailed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Transaction already in progress..
		/// </summary>
		internal static string errTransactionAlreadyInProgress {
			get {
				return ResourceManager.GetString("errTransactionAlreadyInProgress", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Unexpected Application Error
		///
		///Class: {0}
		///Method: {1}
		///Error: {2}.
		/// </summary>
		internal static string errUnexpectedApplicatioErrorDetail {
			get {
				return ResourceManager.GetString("errUnexpectedApplicatioErrorDetail", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Unexpected Application Error.
		/// </summary>
		internal static string errUnexpectedApplicationError {
			get {
				return ResourceManager.GetString("errUnexpectedApplicationError", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to User declined confirmation. Cannot continue..
		/// </summary>
		internal static string errUserDeclinedConfirmation {
			get {
				return ResourceManager.GetString("errUserDeclinedConfirmation", resourceCulture);
			}
		}
	}
}
