//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace MiskoPersist.Resources
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized Strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Strings {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Strings() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (Object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiskoPersist.Resources.Strings", typeof(Strings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized String similar to Confirm?.
		/// </summary>
		internal static String strConfirm {
			get {
				return ResourceManager.GetString("strConfirm", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized String similar to Error!.
		/// </summary>
		internal static String strError {
			get {
				return ResourceManager.GetString("strError", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized String similar to Information.
		/// </summary>
		internal static String strInformation {
			get {
				return ResourceManager.GetString("strInformation", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized String similar to Message received.
		/// </summary>
		internal static String strMessageReceived {
			get {
				return ResourceManager.GetString("strMessageReceived", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized String similar to Message sent.
		/// </summary>
		internal static String strMessageSent {
			get {
				return ResourceManager.GetString("strMessageSent", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized String similar to Processing....
		/// </summary>
		internal static String strPorcessing {
			get {
				return ResourceManager.GetString("strPorcessing", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized String similar to Success!.
		/// </summary>
		internal static String strSuccess {
			get {
				return ResourceManager.GetString("strSuccess", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized String similar to Warning!.
		/// </summary>
		internal static String strWarning {
			get {
				return ResourceManager.GetString("strWarning", resourceCulture);
			}
		}
	}
}
